apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:dev
          imagePullPolicy: Always
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-hub"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-node-chrome
spec:
  selector:
    app: selenium-node-chrome
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP
