name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'self-hosted'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Docker Credentials
        run: |
          echo '{"credsStore":"ecr-login","credHelpers":{"'"${{ secrets.AWS_REPOSITORY }}"'":"ecr-login"}}' > /kaniko/.docker/config.json

      - name: Build and Push Docker Image
        run: |
          /kaniko/executor \
            --context $GITHUB_WORKSPACE \
            --dockerfile $GITHUB_WORKSPACE/Dockerfile \
            --destination ${{ secrets.AWS_REPOSITORY }}:${{ github.ref_name }}
