name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

env:
  AWS_ACCOUNT_ID: 920726247643
  AWS_REGION: us-west-1
  AWS_REPOSITORY: 920726247643.dkr.ecr.us-west-1.amazonaws.com/huseyn01/qa-test-automation
  IMAGE_NAME: automation-app
  TAG: latest
  IMAGE_FULL_NAME: 920726247643.dkr.ecr.us-west-1.amazonaws.com/huseyn01/qa-test-automation:latest
  CLUSTER_NAME: qa-eks-new

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build --tag my-image .

      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v2
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          local-image: my-image
          image: my-image:dev-${{ github.sha }}
